hl.on("hyprland.start", function()
  hl.exec_cmd("waybar")
  hl.exec_cmd("fcitx5 -d")
  hl.exec_cmd("xrdb -merge <<< 'Xft.dpi: 192'")
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("hyprsunset")
  hl.exec_cmd("hyprpaper")
end)
